In [11]:
import numpy as np
import sympy as sp
# What vector times matrix A gives us u and what vector times matrix B gives us v?

A = np.array([[1,2,3],
              [4,5,6],
              [7,8,0]])
B = np.array([[2,-1,1],
              [1,1,2],
              [3,-2,1]])

u = np.array([3,4,-1])
v = np.array([0,-5,1])

print(A)
print(u)
# Numpy does not have row reduction!

Au = sp.Matrix([[1,2,3,3],[4,5,6,4],[7,8,0,-1]]) # Putting vector u at end of vector A
Au.rref() # This answer gives the vector multiplied by matrix A which gives us matrix u 

Bv = sp.Matrix([[2,-1,1,0],[1,1,2,-5],[3,-2,1,1]])
Bv.rref()

# solve Ax=u
x = np.linalg.solve(A, u) # Solve the system Ax=u
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 0]]
[ 3  4 -1]
[-1.66666667  1.33333333  0.66666667]


In [13]:
# A geologist is modeling the interaction b/w 2 GW wells. The equations for hydraulic head at each well are given by: 
# 3x+2y=18 and 4x-5y=-2

import numpy as np

A = np.array([[3,2],
              [4,-5]])
b = np.array([18,-2])

x = np.linalg.solve(A, b)
print(x)

[3.73913043 3.39130435]


In [18]:
# 7x-4y=25 and -3x+11y=2

import numpy as np

A = np.array([[7,-4],
              [-3,11]])
b = np.array([25,2])

x = np.linalg.solve(A, b)
print(x)

[4.35384615 1.36923077]


In [19]:
# 3x3 Linear system solutions: 2x+y-z=8, -3x+4y+2z=-2, and x-5y+3z=9

import numpy as np

A = np.array([[2,1,-1],
              [-3,4,2],
              [1,-5,3]])
b = np.array([8,-2,9])

x = np.linalg.solve(A,b)
print(x)

[5.13636364 1.47727273 3.75      ]
